language: php

php:
    - 5.6
    - 7.0
    - hhvm

matrix:
    allow_failures:
        # - php: hhvm-nightly

install:
    - composer install --no-interaction --prefer-source

script:
    - vendor/bin/tester -p php tests/
